apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: 264907217408.dkr.ecr.ap-south-1.amazonaws.com/node-app-test
        ports:
        - containerPort: 3000